version: '2'

services:
  addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-mainnet

  addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-testnet

  counterparty:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-mainnet
    links:
      - addrindexrs

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - addrindexrs-testnet
      
  http-addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: http-addrindexrs-base-mainnet
    links:
      - bitcoin
      - addrindexrs
      
  http-addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: http-addrindexrs-base-testnet
    links:
      - bitcoin-testnet
      - addrindexrs-testnet      

volumes:
  addrindexrs-data:
  counterparty-data:
