version: '2'

services:
  bitcoin:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-mainnet

  bitcoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  counterparty-classic-addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-addrindexrs-base-mainnet

  counterparty-classic-addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-addrindexrs-base-testnet

  counterparty-classic:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-base-mainnet
    links:
      - bitcoin
      - counterparty-classic-addrindexrs

  counterparty-classic-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-base-testnet
    links:
      - bitcoin-testnet
      - counterparty-classic-addrindexrs-testnet

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base

  counterparty-classic-xcp-proxy:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-xcp-proxy-base-mainnet
    links:
      - redis
      - bitcoin
      - counterparty-classic

  counterparty-classic-xcp-proxy-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-xcp-proxy-base-testnet
    links:
      - redis
      - bitcoin-testnet
      - counterparty-classic-testnet
      
  counterparty-classic-http-addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-http-addrindexrs-base-mainnet
    links:
      - bitcoin
      - counterparty-classic-addrindexrs
      
  counterparty-classic-http-addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-classic-http-addrindexrs-base-testnet
    links:
      - bitcoin-testnet
      - counterparty-classic-addrindexrs-testnet

volumes:
  bitcoin-data:
  counterparty-classic-addrindexrs-data:
  counterparty-classic-data:
