version: '2'

# Data volumes defined in these services (which must be defined in child templates):
# bitcoin-data
# counterparty-classic-counterparty-data
# counterparty-classic-counterblock-data
# mongodb-data

services:
  bitcoin-base:
    build:
      context: ./extras/docker/bitcoin
    volumes:
      - ./config/bitcoin:/root/.bitcoin-config
      - bitcoin-data:/root/.bitcoin/
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    restart: "unless-stopped"

  bitcoin-base-mainnet:
    hostname: ${HOSTNAME_BASE}-bc
    extends:
      service: bitcoin-base
    ports:
      - "8332:8332"
      - "28832:28832"
    environment:
      - PARAMS=-conf=/root/.bitcoin-config/bitcoin.conf

  bitcoin-base-testnet:
    hostname: ${HOSTNAME_BASE}-bc-t
    extends:
      service: bitcoin-base
    ports:
      - "18332:18332"
      - "38832:38832"
    environment:
      - PARAMS=-conf=/root/.bitcoin-config/bitcoin.testnet.conf

  counterparty-classic-addrindexrs-base:
    build:
      context: ./src/counterparty-classic-addrindexrs
      dockerfile: ./Dockerfile
    command: cargo run --release -- -vvvv
    volumes:
      - ./config/counterparty-classic-addrindexrs:/root/.config/addrindexrs
      - counterparty-classic-addrindexrs-data:/home/user/db/
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    environment:
      - ADDRINDEXRS_JSONRPC_IMPORT=1
      - ADDRINDEXRS_TXID_LIMIT=15000
      - "ADDRINDEXRS_COOKIE=rpc:rpc"
    restart: "unless-stopped"  

  counterparty-classic-addrindexrs-base-mainnet:
    hostname: ${HOSTNAME_BASE}-idxd
    extends:
      service: counterparty-classic-addrindexrs-base
    ports:
      - "8432:8432"
    environment:
      - "ADDRINDEXRS_INDEXER_RPC_ADDR=0.0.0.0:8432"
      - "ADDRINDEXRS_DAEMON_RPC_ADDR=bitcoin:8332"

  counterparty-classic-addrindexrs-base-testnet:
    hostname: ${HOSTNAME_BASE}-idxd-t
    extends:
      service: counterparty-classic-addrindexrs-base
    ports:
      - "18432:18432"
    environment:
      - "ADDRINDEXRS_INDEXER_RPC_ADDR=0.0.0.0:18432"
      - ADDRINDEXRS_NETWORK=testnet
      - "ADDRINDEXRS_DAEMON_RPC_ADDR=bitcoin-testnet:18332"

  counterparty-classic-base:
    build:
      context: ./src/counterparty-classic-lib
    volumes:
      - ./config/counterparty-classic:/root/.config/counterparty
      - counterparty-classic-data:/root/.local/share/counterparty
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"
    restart: "unless-stopped"    

  counterparty-classic-base-mainnet:
    hostname: ${HOSTNAME_BASE}-cp
    extends:
      service: counterparty-classic-base
    ports:
      - "4000:4000"
    environment:
      - PARAMS=--config-file=/root/.config/counterparty/server.conf
      - BTC_NETWORK=mainnet
      - NO_BOOTSTRAP=${NO_BOOTSTRAP}
      
  counterparty-classic-base-testnet:
    hostname: ${HOSTNAME_BASE}-cp-t
    extends:
      service: counterparty-classic-base
    ports:
      - "14000:14000"
    environment:
      - PARAMS=--config-file=/root/.config/counterparty/server.testnet.conf
      - BTC_NETWORK=testnet
      - NO_BOOTSTRAP=${NO_BOOTSTRAP}
      
  counterparty-classic-counterblock-base:
    build:
      context: ./src/counterparty-classic-counterblock
    volumes:
      - ./config/counterparty-classic-counterblock:/root/.config/counterblock
      - counterparty-classic-counterblock-data:/root/.local/share/counterblock
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"
    restart: "unless-stopped"    

  counterparty-classic-counterblock-base-mainnet:
    hostname: ${HOSTNAME_BASE}-cb
    extends:
      service: counterparty-classic-counterblock-base
    ports:
      - "4100:4100"
    environment:
      - PARAMS=--config-file=/root/.config/counterblock/server.conf

  counterparty-classic-counterblock-base-testnet:
    hostname: ${HOSTNAME_BASE}-cb-t
    extends:
      service: counterparty-classic-counterblock-base
    ports:
      - "14100:14100"
      - "14101:14101"
      - "14102:14102"
    environment:
      - PARAMS=--config-file=/root/.config/counterblock/server.testnet.conf

  counterparty-classic-counterwallet-base:
    hostname: ${HOSTNAME_BASE}-cw
    build:
      context: ./src/counterparty-classic-counterwallet
    volumes:
      - ./config/counterparty-classic-counterwallet/ssl:/ssl_config
      - counterparty-classic-counterblock-data:/counterblock_data
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    ports:
      - "80:80"
      - "443:443"

  mongodb-base:
    hostname: ${HOSTNAME_BASE}-mongo
    image: mongo:3.2
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    ports:
      - ${MONGODB_HOST_INTERFACE}:27017:27017

  redis-base:
    hostname: ${HOSTNAME_BASE}-redis
    image: redis:3.2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"

  counterparty-classic-xcp-proxy-base:
    build:
      context: ./src/counterparty-classic-xcp-proxy
      dockerfile: ./Dockerfile
    volumes:
      - ./config/counterparty-classic-xcp-proxy:/root/.config/xcp-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    environment:
      - INTERVAL_CHECK_COUNTERPARTY_PARSED=1000

  counterparty-classic-xcp-proxy-base-mainnet:
    hostname: ${HOSTNAME_BASE}-prx
    extends:
      service: counterparty-classic-xcp-proxy-base
    ports:
      - "8097:8097"
      - "8098:8098"
    environment:
      - HTTP_PORT=8097
      - HTTPS_PORT=8098
      - ADDRINDEXRS_URL=tcp://addrindexrs:8432
      - BITCOIN_ZMQ_URL=tcp://bitcoin:28832
      - REDIS_URL=redis://redis:6379/8
      - SECRETS_PATH=/root/.config/xcp-proxy/secrets

  counterparty-classic-xcp-proxy-base-testnet:
    hostname: ${HOSTNAME_BASE}-prx-t
    extends:
      service: counterparty-classic-xcp-proxy-base
    ports:
      - "18097:18097"
      - "18098:18098"
    environment:
      - HTTP_PORT=18097
      - HTTPS_PORT=18098
      - ADDRINDEXRS_URL=tcp://addrindexrs-testnet:8432
      - BITCOIN_ZMQ_URL=tcp://bitcoin-testnet:38832
      - REDIS_URL=redis://redis:6379/9
      - SECRETS_PATH=/root/.config/xcp-proxy/secrets-testnet

  counterparty-classic-http-addrindexrs-base:
    build:
      context: ./src/counterparty-classic-http-addrindexrs
    volumes:
      - ./config/counterparty-classic-http-addrindexrs:/root/.config/http-addrindexrs
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"

  counterparty-classic-http-addrindexrs-base-mainnet:
    hostname: ${HOSTNAME_BASE}-ha
    extends:
      service: counterparty-classic-http-addrindexrs-base
    ports:
      - "9000:8335"
      - "9001:9001"
    environment:
      - DOTENV_CONFIG_PATH=/root/.config/http-addrindexrs/server.conf
      
  counterparty-classic-http-addrindexrs-base-testnet:
    hostname: ${HOSTNAME_BASE}-ha-t
    extends:
      service: counterparty-classic-http-addrindexrs-base
    ports:
      - "19000:18335"
      - "19001:19001"
    environment:
      - DOTENV_CONFIG_PATH=/root/.config/http-addrindexrs/server.testnet.conf    
